---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 10
    groups:
      react:
        patterns:
          - "react"
          - "@types/react"
          - "react-dom"
          - "@types/react-dom"

   # github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 10
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "Dependencies"
    commit-message:
      prefix: "gha"
      include: "scope"
